# Generated by Django 2.0.6 on 2018-07-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180625_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=50)),
                ('moment', models.CharField(max_length=50)),
                ('siteNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='myFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathOf', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('siteNumber', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
