# Generated by Django 2.0.6 on 2018-07-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_site_site_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_number',
            new_name='siteNumber',
        ),
    ]
