# Generated by Django 2.0.6 on 2018-07-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180716_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='siteNumber',
            new_name='site_number',
        ),
    ]
