# Generated by Django 2.0.6 on 2018-07-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180716_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordonates',
            old_name='siteNumber',
            new_name='site_number',
        ),
        migrations.AddField(
            model_name='site',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
